### ISSUE TITLE
Some entries are not added by nansat_ingestor get_or_create, and some are hardcoded

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/django-geo-spaas#26]
- [x] Data center name is hardcoded to "NERSC". It should rather be 
`sname = pti.get_gcmd_provider('nersc')['Short_Name']`

- [x] `isocatname = 'Oceans'` -> 
`isocatname = pti.get_iso19115_topic_category('oceans')['iso_topic_category']`

- [x] `gcmd_location` should also be added

Since we are using try-except clauses for these cases, I am not sure how to best test this...

**Comment by akorosov** [comment]
This was partly fixed in #13 but the issue still persists:
If the Nansat mapper returns metadata 'ISO Topic Category' then Dataset is created with:

`Dataset(..., ISO_topic_category=metadata['ISO Topic Category'], ...)`
and that raises an error:

`ValueError: Cannot assign "'Oceans'": "Dataset.ISO_topic_category" must be a "ISOTopicCategory" instance.`

The same happens to Datacenter.

I would suggest to make it more strict and demand from mappers to return full JSON both for ISOTopicCategory and  Datacenter just like with platform and instrument. And then to handle them in Nansat ingestor the same way as platform and instrument.

Other char fields (summary, ...) can be handled with default values.

**Comment by akorosov** [comment]
I would also to propose to follow a convention on metadata naming:
let it be only block letters separated by underscore:
```
iso_topic_category
data_center
entry_id
entry_title
```
etc
